### ISSUE TITLE
[Bug] Game fail to boot up in 1.19.2

### ISSUE THREAD

**Issue by DaGamerFiles** [Kira-NT/sync-fabric#31]
### What happened?

The game simply won't run with the current 1.19.2 build. Tried disabling some mods but to no avail. Creating a fresh instances still won't make it run.

### Version

mc1.19.1-4.3-sources

### Minecraft Version

1.19.2

### Fabric API Version

0.62.0+1.19.2

### Installation Source

CurseForge

### Logs

```shell
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sync (Fabric)' (sync) ${version} with any version that is compatible with:
		 - fabricloader 0.14.9
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'Sync (Fabric)' (sync) ${version} requires version ${fabric} of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.9!
	 - Mod 'Sync (Fabric)' (sync) ${version} requires version ${minecraft} of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
```

### Other Mods

```shell
None
```

### Additional Information

Launcher is PolyMC 1.4.1 on Windows 11 22H2. PolyMC listed the mod's version as `${version}`.

**Comment by Kira-NT** [comment]
Oh, I see your problem. You've downloaded a wrong file. What you're looking for is `sync-mc1.19.1-4.3.jar` (the main one), not `mc1.19.1-4.3-sources.jar` (this is an additional file for developing purposes)
