### ISSUE TITLE
[Bug] The came stuck in transition from one shell to the next

### ISSUE THREAD

**Issue by Nofelxzone** [Kira-NT/sync-fabric#34]
### What happened?

I'm running it on quilt and with a lot of mods but every time and to transfer to another clone after "dying" I'm and stuck at the top of the world after selecting my origins

### Version

v1.10.4 for Fabric/Quilt&MC1.19

### Minecraft Version

1.19.2

### Fabric API Version

none I'm using quilt 

### Installation Source

CurseForge

### Logs

```shell
[17:40:25] [Server thread/INFO]: [Nofelxzone: Set the time to 1000]
[17:40:25] [Render thread/INFO]: [System] [CHAT] Set the time to 1000
[17:40:42] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Parameter specified as non-null is null: method com.williambl.haema.component.EntityVampireComponent.readFromNbt, parameter tag
	at com.williambl.haema.component.EntityVampireComponent.readFromNbt(EntityVampireComponent.kt) ~[haema-1.10.4+1.19.jar:?]
	at dev.kir.sync.compat.cca.CCAShellStateComponent.clone(CCAShellStateComponent.java:49) ~[sync-mc1.19.1-4.3.jar:?]
	at dev.kir.sync.api.shell.ShellStateComponent$CombinedShellStateComponent.clone(ShellStateComponent.java:222) ~[sync-mc1.19.1-4.3.jar:?]
	at net.minecraft.class_3222.apply(class_3222.java:10942) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.sync(class_3222.java:10908) ~[client-intermediary.jar:?]
	at dev.kir.sync.api.networking.SynchronizationRequestPacket.execute(SynchronizationRequestPacket.java:62) ~[sync-mc1.19.1-4.3.jar:?]
	at dev.kir.sync.api.networking.ServerPlayerPacket.lambda$register$0(ServerPlayerPacket.java:57) ~[sync-mc1.19.1-4.3.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:40:55] [Server thread/INFO]: Saving and pausing game...
```

### Other Mods

```shell
alternate-current-mc1.19-1.4.0.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.4.62-fabric.jar
artifacts-7.1.1+fabric.jar
BetterAdvancements-Fabric-1.19.2-0.2.2.142.jar
bewitchment-1.19-6.jar
bewitchmentplus-1.19-9.jar
blabber-0.4.0-standalone.jar
cardinal-components-api-5.0.2.jar
caveore-fabric-1.19-2.4.jar
cloth-config-8.2.88-fabric.jar
Clumps-fabric-1.19.2-9.0.0+11.jar
collective-fabric-1.19.2-5.22.jar
configured-fabric-2.0.0-1.19.2.jar
crawl-0.11.1.jar
data-attributes-1.4.0.jar
extra_thicc_packets-1.0.jar
fabric-language-kotlin-1.8.7+kotlin.1.7.22.jar
Fastload+1.19.2-2.4.4.jar
ferritecore-5.0.3-fabric.jar
ForgeConfigAPIPort-v4.2.9-1.19.2-Fabric.jar
geckolib-fabric-1.19-3.1.37.jar
haema-1.10.4+1.19.jar
harvestwithease-1.19.2-4.0.0.3-fabric.jar
Herobrine-Revamped Official.jar
homing_ender_eye-1.19.2-1.3.0.jar
icarus-1.13.jar
impersonate-2.8.0-standalone.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.19.2-0.10.2.jar
memoryleakfix-1.19.3-0.7.0.jar
mermod-fabric-2.21.jar
midnightlib-fabric-1.0.0.jar
minecells-1.3.3.jar
mineralchance-fabric_1.19.2-2.2.jar
OPChanter-1.19.2-1.0.0-fabric.jar
Origins-1.19.2-1.7.1.jar
Origins-Classes-1.19-1.4.0.jar
owo-lib-0.8.5+1.19.jar
pal-1.6.0.jar
passiveshield-fabric_1.19.2-2.7.jar
Patchouli-1.19.2-77-FABRIC.jar
Pehkui-3.6.0+1.14.4-1.19.3.jar
playerex-3.5.0.jar
qfapi-4.0.0-beta.26_qsl-3.0.0-beta.25_fapi-0.72.0_mc-1.19.2.jar
relicex-3.2.7.jar
requiem-2.0.0-beta.16.jar
RoughlyEnoughItems-9.1.580.jar
satin-1.9.0.jar
servercore-1.3.3-1.19.2.jar
smoke-suppression-1.0.13+MC1.19-1.19.2.jar
smoothboot-fabric-1.19-1.7.1.jar
smoothchunk-fabric-1.19.1-2.0.jar
starlight-1.1.1+fabric.ae22326.jar
sync-mc1.19.1-4.3.jar
things-0.2.20+1.19.jar
Towns-and-Towers-1.19.2-1.9.jar
travelers-backpack-1.19.2-8.2.9.jar
trinkets-3.4.1.jar
```

### Additional Information

TLauncher

**Comment by Kira-NT** [comment]
It's the same one as #30. I'll surely fix the problem when there would be a possibility for me to finally update my mods :)

Closing this one as a duplicate, so if you want to track this problem's status, you may subscribe to the parent issue

**Comment by Nofelxzone** [comment]
Okay Thanks
